// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSM.Infrastructure.Data;

#nullable disable

namespace PSM.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811083026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSM.Domain.Entities.Allergie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BewohnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BewohnerId");

                    b.ToTable("Allergien");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Bestellposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LebensmittelbestellungId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lebensmittelname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Menge")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LebensmittelbestellungId");

                    b.ToTable("Bestellpositionen");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Bewohner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Geburtsdatum")
                        .HasColumnType("date");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StandortBewohnerNummer")
                        .HasColumnType("integer");

                    b.Property<int>("StandortId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zimmernummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StandortId", "StandortBewohnerNummer")
                        .IsUnique();

                    b.ToTable("Bewohner");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Ernaehrung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abendessen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Besonderheiten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BewohnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fruehstueck")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kostform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mittagessen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BewohnerId")
                        .IsUnique();

                    b.ToTable("Ernaehrungen");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Essensausgabe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BewohnerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ErledigtAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErledigtVonBenutzerId")
                        .HasColumnType("text");

                    b.Property<bool>("IstErledigt")
                        .HasColumnType("boolean");

                    b.Property<string>("Mahlzeit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BewohnerId");

                    b.ToTable("Essensausgaben");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Lebensmittelbestellung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BearbeitetVonBenutzerId")
                        .HasColumnType("text");

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Bestelldatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ErledigtAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVonBenutzerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Lieferdatum")
                        .HasColumnType("date");

                    b.Property<int>("StandortId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StandortId");

                    b.ToTable("Lebensmittelbestellungen");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Pflegedokumentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BewohnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErstelltVonBenutzerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeaendertVonBenutzerId")
                        .HasColumnType("text");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MitSpracheErstellt")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BewohnerId");

                    b.ToTable("Pflegedokumentationen");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Standort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Standorte");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Allergie", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Bewohner", "Bewohner")
                        .WithMany()
                        .HasForeignKey("BewohnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bewohner");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Bestellposition", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Lebensmittelbestellung", "Lebensmittelbestellung")
                        .WithMany()
                        .HasForeignKey("LebensmittelbestellungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lebensmittelbestellung");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Bewohner", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Standort", "Standort")
                        .WithMany()
                        .HasForeignKey("StandortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Standort");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Ernaehrung", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Bewohner", "Bewohner")
                        .WithOne()
                        .HasForeignKey("PSM.Domain.Entities.Ernaehrung", "BewohnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bewohner");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Essensausgabe", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Bewohner", "Bewohner")
                        .WithMany()
                        .HasForeignKey("BewohnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bewohner");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Lebensmittelbestellung", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Standort", "Standort")
                        .WithMany()
                        .HasForeignKey("StandortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Standort");
                });

            modelBuilder.Entity("PSM.Domain.Entities.Pflegedokumentation", b =>
                {
                    b.HasOne("PSM.Domain.Entities.Bewohner", "Bewohner")
                        .WithMany()
                        .HasForeignKey("BewohnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bewohner");
                });
#pragma warning restore 612, 618
        }
    }
}
